### ISSUE TITLE
Member info isn't updated until a rebuilt

### ISSUE THREAD

**Issue by alexdor** [ossn/ossn-frontend#152]
## Expected Behavior
When a member page is loaded, the frontend should display the cached version (the one that is prebuild by gatsby) and then it should request user's data from the backend in order to show any updated information since the last rebuilt.

## Actual Behavior
The frontend only displays the cached (prebuild) version of the page

**Comment by iropal** [comment]
@alexdor when we talked about this issue my understanding was that when there is a change in the data at the backend, netlify would trigger the rebuild task so there would be no such need. Has something changed?

**Comment by alexdor** [comment]
No it hasn't changed. But the rebuild doesn't solve the issue of stale data until it's finished (which takes around 5')  

The workflow should be: 
* Gatsby builds a page with the member info prepopulated. 
* The page with the prepopulated member info is served to the client
* When the listing mounts the member info is re-requested from the backend in order to get any new updates

The current workflow is:
* Gatsby builds a page with the member info prepopulated. 
* The page with the prepopulated member info is served to the client
