### ISSUE TITLE
Club events have not been tested, need some data in the backend

### ISSUE THREAD

**Issue by iropal** [ossn/ossn-frontend#187]

**Comment by alexdor** [comment]
A few events have been added for the club "Dedomena".
A few issues that arise are:
- [ ] There is no date presented to the user
- [ ] Past events are shown the same as current events
- [ ] Event's aren't sorted based on the date that they start

**Comment by iropal** [comment]
@alexdor I could not add location to the events in the backend.
I solved all the other issues besides the full description which I don't think that there is enough space in the sidebar to print it as well. It could be used in the future in an event page with the image I found in the backend. For the moment there is no design and no further specification for the events.
@bacharakis What is your opinion on this?

**Comment by alexdor** [comment]
@iropal there seems to be an issue with the admin on the dev env. I've manually added locations to all the events so you can test it.

**Comment by iropal** [comment]
@alexdor though I can see the locations in the admin UI, the query is returning null for all of them.

**Comment by alexdor** [comment]
@iropal should be fixed. This issue should be fixed also when requesting multiple clubs. Let me know if you face any other issues :)

**Comment by iropal** [comment]
Location linked to openstreetmaps has been added. @bacharakis can we consider this issue fixed?

**Comment by bacharakis** [comment]
I commented specifically #227 , so yeah we can close this! Thank you
