### ISSUE TITLE
Broken link on footer

### ISSUE THREAD

**Issue by bacharakis** [ossn/ossn-frontend#200]
in the footer there is the "affiliations" link which leads to a 404.
Was that supposed to lead to "organizations"?

**Comment by iropal** [comment]
@bacharakis There has been a confusion since the designs where both affiliations (on footer) and organizations (on header) exist. It makes sense to change both the text and the link to lead to organizations.

**Comment by alexdor** [comment]
Login/Signup button doesn’t work as well

**Comment by iropal** [comment]
I'll fix that with #190

**Comment by iropal** [comment]
@bacharakis do you want the link title to be Affiliations or Organizations?
