### ISSUE TITLE
Club title should be clickable 

### ISSUE THREAD

**Issue by bacharakis** [ossn/ossn-frontend#203]
Expected behavior: When clicking on Club's title should take you to the club's page
![screenshot from 2019-02-18 16-11-08](https://user-images.githubusercontent.com/1435040/52959977-f8dfb700-3397-11e9-9408-e4d29c5d0f7d.png)

**Comment by alexdor** [comment]
Wouldn’t it be better if the whole box was clickable?

**Comment by iropal** [comment]
@bacharakis both can be easily done, do you prefer to make the title clickable or the whole box? The second option seems more usable, especially in touch devices.

**Comment by iropal** [comment]
@bacharakis I made the title clickable as the issue described. I did not want to wait since it is a P1 issue. I can make the whole box clickable if you want.

**Comment by bacharakis** [comment]
Thank you @iropal , yes, making the whole box clickable makes more sense, especially for mobile view
