### ISSUE TITLE
Become a member design is broken

### ISSUE THREAD

**Issue by bacharakis** [ossn/ossn-frontend#204]
![screenshot from 2019-02-18 16-19-51](https://user-images.githubusercontent.com/1435040/52960448-17927d80-3399-11e9-8129-09fc87c30a0e.png)

**Comment by bacharakis** [comment]
Becoming a member is also not working. When clicking the button, it disappears and if you refresh it asks you again to become a member of this club

**Comment by iropal** [comment]
@bacharakis The button must be a regression. At some commit the order of inclusion of css files must have changed. It will be fixed with  #190. 
The second issue is part of #190.
