### ISSUE TITLE
Become a member is mulfuctioning 

### ISSUE THREAD

**Issue by bacharakis** [ossn/ossn-frontend#205]
![screenshot from 2019-02-18 16-23-13](https://user-images.githubusercontent.com/1435040/52960628-81128c00-3399-11e9-9179-a504b06043bd.png)
I became a member of the same club three times

STR:

1. Open the club profile
2. Click the become a member
3. Refresh
4. Click the become a member
5. Refresh
6. Click the become a member

**Comment by bacharakis** [comment]
![screenshot from 2019-02-18 16-27-14](https://user-images.githubusercontent.com/1435040/52960906-1281fe00-339a-11e9-8d52-2074f9cb8598.png)

**Comment by alexdor** [comment]
Should be fixed with ossn/ossn-backend@e5fdff5bdaf6d1110659d521c828b454de9fa0ed
