### ISSUE TITLE
Refreshing member's page, makes edit button disappear

### ISSUE THREAD

**Issue by alexdor** [ossn/ossn-frontend#208]
If you log in and you go to your profile and refresh the page, the edit button disappears.

**Comment by alexdor** [comment]
@iropal does your current solution solve the issue for newly created users? I think that newly created users don't have the member props, am I wrong?

**Comment by iropal** [comment]
@alexdor I did not check. It was not described in the issue.

**Comment by iropal** [comment]
@alexdor when logging in with a newly created user there is not edit functionality. I guess this is a totally different issue.

**Comment by iropal** [comment]
@alexdor since you reopened this issue, if you consider this done pls close it.

**Comment by alexdor** [comment]
Yeah looks fixed : )

> Note: The issues doesn't have to described all the possible states of the app, a user that already exists and a user that logged in for the first time should have the same experience
