### ISSUE TITLE
Include noreferrer and noopener to all external links

### ISSUE THREAD

**Issue by alexdor** [ossn/ossn-frontend#214]
Include target _blank, noreferrer and noopener to all external links, for example in :
https://github.com/ossn/ossn-frontend/blob/92c0fd9307b1833d7e7e9364976baf119b75f66e/src/components/navigation/footer-navigation/footer-navigation.js#L52

**Comment by siddhant1** [comment]
Will work on it soon

**Comment by shakti97** [comment]
Can i take this issue if still opened?
