### ISSUE TITLE
Jobs & Annoucements timestamp presented wrong

### ISSUE THREAD

**Issue by bacharakis** [ossn/ossn-frontend#225]
Even though in the backend is added properly, in the front-end it present 1970
![screenshot from 2019-02-22 11-34-57](https://user-images.githubusercontent.com/1435040/53259951-b20ffb00-36d0-11e9-8e92-7310e74bf544.png)
![screenshot from 2019-02-22 11-34-52](https://user-images.githubusercontent.com/1435040/53259952-b20ffb00-36d0-11e9-8482-28e38d7b9410.png)

**Comment by iropal** [comment]
Fixed with pr #239
