### ISSUE TITLE
Club page has mutiple isses after refactor

### ISSUE THREAD

**Issue by iropal** [ossn/ossn-frontend#246]
1. GithubUrl value cannot be saved. 
2. History is not reverted when we cancel edit.
3. Content is not updated after first load.
4. When fields have empty values the club cannot be saved

**Comment by iropal** [comment]
Pr #245 solves 1 and 4 but when we to save empty github url we get error: Unhandled promise rejection Error: "GraphQL error: pq: duplicate key value violates unique constraint "clubs_github_url_key""

**Comment by alexdor** [comment]
pq: duplicate key value violates unique constraint "clubs_github_url_key" Means that there is another club with the same url, I've removed this constrain now, let me know if you face it again.
