### ISSUE TITLE
Legal requires to have a checkbox, confirming that the user is older than 18 years old.

### ISSUE THREAD

**Issue by alexdor** [ossn/ossn-frontend#258]
Legal requires to have a checkbox, confirming that the user is older than 18 years old.

_Originally posted by @bacharakis in https://github.com/ossn/ossn-frontend/issues/188#issuecomment-464812749_

**Comment by iropal** [comment]
@alexdor pls notify when this is added in the backend.

**Comment by alexdor** [comment]
@iropal should be deployed

**Comment by nik72619c** [comment]
Is this issue free to work on?

**Comment by alexdor** [comment]
There is already a pull request open for this issue ( #261 )

**Comment by iropal** [comment]
@bacharakis The field has been added. By default it is not checked. Do we consider this issue fixed or do we need something more or different?

**Comment by bacharakis** [comment]
Perfect! Not being checked by default is what exactly we need
