### ISSUE TITLE
Signing up using email UI/UX looks broken

### ISSUE THREAD

**Issue by bacharakis** [ossn/ossn-frontend#277]
It's not clear that the email shown is the "Name", neither all the available information for editing your profile.
And of course, the design is broken
![Screenshot from 2019-03-14 18-07-48](https://user-images.githubusercontent.com/1435040/54376794-1dbc0700-4684-11e9-968b-3a348b2aa5a7.png)
![Screenshot from 2019-03-14 18-05-40](https://user-images.githubusercontent.com/1435040/54376795-1e549d80-4684-11e9-8c5b-fa521a0e202b.png)

**Comment by iropal** [comment]
@bacharakis I managed to reproduce the layout issue in safari. Pr #278 should be fixing it. 
I don't know in which browser you experienced the issue. 
The new layout can be in preview: https://deploy-preview-278--zen-euclid-6d318e.netlify.com/
If you keep experiencing the issue please let me know and give some more info (browser, operating system).
I changed the member form ux as well by adding labels and icons. What do you think about it?
<img width="1232" alt="Screenshot 2019-03-15 at 14 34 02" src="https://user-images.githubusercontent.com/5672619/54431610-8f04c400-472f-11e9-8484-d4aefce3cc23.png">

**Comment by bacharakis** [comment]
Thanks @iropal and @alexdor . However that doesn't solve the issue about forcing users to change their name or add new information on their profile.
![Screenshot from 2019-03-15 20-41-09](https://user-images.githubusercontent.com/1435040/54457900-eb350b80-4762-11e9-8da3-8d9af10277e9.png)

**Comment by iropal** [comment]
@bacharakis @alexdor I just created a new account at the live website to be sure this time and the issue seem solved. (I could not reproduce it in my local environment)
@bacharakis Is it solved for you?
@alexdor can you please remove user: 121 from the live website? (https://ossn.club/members/121/)

**Comment by alexdor** [comment]
Done :)

**Comment by bacharakis** [comment]
YES! Thank you @iropal
