### ISSUE TITLE
Add link to GitHub in bottom navigation

### ISSUE THREAD

**Issue by LucyeoH** [ossn/ossn-frontend#289]
like in activate footer
https://activate.mozilla.community/

**Comment by csrs** [comment]
@LucyeoH What text do you want this link (https://github.com/mozilla/activate.mozilla.community/issues) to have?

**Comment by LucyeoH** [comment]
I think my recommendation was to have a link to THIS GitHub repo (https://github.com/ossn/ossn-frontend) linked from the OSSN website footer, in the same way that the activate repo is linked from the footer on the activate website.

**Comment by csrs** [comment]
Ok, that makes more sense. I must have read 'like' as 'link'

**Comment by csrs** [comment]
PR #296
