### ISSUE TITLE
Theme club page

### ISSUE THREAD

**Issue by iropal** [ossn/ossn-frontend#45]
Apply icons, font styles, shadow box, shapes as is the design.

**Comment by iropal** [comment]
@dPliakos I know that the branch I merged work was WIP but I have made a list of the remaining tasks :)
- [ ] club-full__title top distance
- [ ] club-full__subtitle font and color
- [ ] Become a member text ,fond size , icon size. 
- [ ] Icon distances from text at the sidebar are small
- [ ] We need background images at the sidebar
- [ ] club-info__item needs padding both on top and bottom to ensure minimum distances on the vertical axis
- [ ] All vertical distances need a check
- [ ] We need an image at the header :)
- [ ] And last but not least the shapes!

**Comment by dPliakos** [comment]
Great, I will continue this one at a new branch
