### ISSUE TITLE
Leaders tools polishing

### ISSUE THREAD

**Issue by iropal** [ossn/ossn-frontend#8]
1. eslint disable needs to be removed and any possible error fixed.
2. Icons should be moved to local storage (like organization logos)
3. Expand - collapse icons should use the icon font and have the correct size (see footer)
4. External link color has changed to #12B4BC
5. Mobile distances need some love. The layout-2col__coll extra distance in mobile can be overwritten specifically for this component. 
6. We need a hover effect, let's use the brand color for the text.
7. I'd remove the focus outline to handle focus outlines side-wide and not per component.

**Comment by dPliakos** [comment]
About the 6.
@iropal  the brand color is [already used](https://github.com/ossn/ossn-frontend/blob/master/src/components/components/leader-tools/leader-tools.scss#L42) for the hover effect, but is too dark and at that size of font, the change is not notable.  I used a background color on hover effect. What do you think about it?

**Comment by iropal** [comment]
The background change effect is interesting, but it is not on the link which does to take up the whole line + with the underline that is contained it seems a bit weird (I'll remove the underline from the last link to be consistent with the design). Since this is almost done I'll merge the pull request and do a couple of adjustments myself to close the issue.
