### ISSUE TITLE
Add real content to FAQ page

### ISSUE THREAD

**Issue by iropal** [ossn/ossn-frontend#93]
It can be found at: https://opensource.mozilla.community/faq-page/

**Comment by dPliakos** [comment]
The[ current FAQ page](https://opensource.mozilla.community/faq-page/) does not have groups and has styling and links. 

On the other hand the design shows plain text and grouped questions. Should we change the implementation to support styled text and links ? (as markdown ?)

**Comment by iropal** [comment]
@dPliakos I changed the implementation and merged it to master. Just insert the content in faq-page.js as in the examples (You can insert the content as html). If it needs some extra styling we can apply it afterwards, though the content just has links and lists which might work out of the box.
Checking the content I, I think all of the existing content can be mapped to Joining OSSN (two first) and Registering a club (rest) groups. Leave the rest empty :)
